// lib/demoData.js — Hardcoded in-memory museum data (DB-free demo)
export const DEMO_PERIODS = [
  { id: "medieval", name: "Medieval Art", startYear: 500, endYear: 1400, region: "Europe", summary: "The medieval art of the Western world covers a vast scope of time and place, with over 1000 years of art in Europe.", _count: { artists: 3 } },
  { id: "renaissance", name: "Renaissance", startYear: 1400, endYear: 1600, region: "Italy/Europe", summary: "Renaissance art (1350–1620) is the painting, sculpture, and decorative arts of the period of European history known as the Renaissance.", _count: { artists: 5 } },
  { id: "baroque", name: "Baroque", startYear: 1600, endYear: 1750, region: "Europe", summary: "Baroque art is dramatic, richly colored, and filled with movement, lighting, and intense emotions.", _count: { artists: 5 } },
  { id: "rococo", name: "Rococo", startYear: 1700, endYear: 1780, region: "France/Europe", summary: "Rococo art emerged in France in the early 18th century, with ornate decoration and pastel colors.", _count: { artists: 3 } },
  { id: "neoclassicism", name: "Neoclassicism", startYear: 1750, endYear: 1850, region: "Europe", summary: "Neoclassicism revived classical antiquity, with severe, clear forms and noble subject matter.", _count: { artists: 2 } },
  { id: "romanticism", name: "Romanticism", startYear: 1800, endYear: 1850, region: "Europe", summary: "Romanticism emphasized emotion, individualism, and the glorification of nature and historical events.", _count: { artists: 4 } },
  { id: "realism", name: "Realism", startYear: 1840, endYear: 1880, region: "France/Europe", summary: "Realism rejected Romanticism and sought to depict working-class subjects and contemporary life truthfully.", _count: { artists: 2 } },
  { id: "impressionism", name: "Impressionism", startYear: 1860, endYear: 1890, region: "France", summary: "Impressionism captured light and atmosphere with visible brushstrokes and vibrant color.", _count: { artists: 5 } },
  { id: "post-impressionism", name: "Post-Impressionism", startYear: 1880, endYear: 1910, region: "France/Europe", summary: "Post-Impressionism extended Impressionism while rejecting its limitations: greater emotion, structure, and symbolism.", _count: { artists: 4 } },
  { id: "expressionism", name: "Expressionism", startYear: 1905, endYear: 1925, region: "Germany/Europe", summary: "Expressionism distorted reality to express emotional experience rather than physical reality.", _count: { artists: 3 } },
  { id: "cubism", name: "Cubism", startYear: 1907, endYear: 1922, region: "France", summary: "Cubism broke objects into geometric forms and reassembled them from multiple viewpoints.", _count: { artists: 3 } },
  { id: "surrealism", name: "Surrealism", startYear: 1920, endYear: 1950, region: "Europe", summary: "Surrealism sought to release the creative potential of the unconscious mind through dreamlike imagery.", _count: { artists: 3 } },
  { id: "abstract-expressionism", name: "Abstract Expressionism", startYear: 1940, endYear: 1960, region: "USA", summary: "Abstract Expressionism combined abstract art with emotional intensity, often on a large scale.", _count: { artists: 3 } },
  { id: "pop-art", name: "Pop Art", startYear: 1955, endYear: 1970, region: "UK/USA", summary: "Pop Art drew on popular and commercial culture: advertising, comic books, mass media.", _count: { artists: 2 } },
];

// Wikimedia Commons'tan popüler görseller (public domain)
const WIKI = (path) => `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}`;

export const DEMO_ARTISTS = {
  medieval: [
    { id: "giotto-di-bondone", name: "Giotto di Bondone", birthYear: 1267, deathYear: 1337, nationality: "Italian", summary: "Pioneer of Renaissance painting, broke from Byzantine tradition with more naturalistic figures.", movements: "Medieval", portrait: WIKI("9/96/Giotto_di_Bondone.jpg/400px-Giotto_di_Bondone.jpg"), _count: { works: 4 } },
    { id: "duccio-di-buoninsegna", name: "Duccio di Buoninsegna", birthYear: 1255, deathYear: 1319, nationality: "Italian", summary: "One of the most influential Sienese painters of the early Renaissance.", movements: "Medieval", portrait: WIKI("5/5b/Duccio_di_Buoninsegna_-_Madonna_in_Maesta.jpg/400px-Duccio_di_Buoninsegna_-_Madonna_in_Maesta.jpg"), _count: { works: 4 } },
    { id: "jan-van-eyck", name: "Jan van Eyck", birthYear: 1390, deathYear: 1441, nationality: "Flemish", summary: "Flemish painter considered one of the foremost of the Early Netherlandish school.", movements: "Medieval", portrait: WIKI("0/02/Jan_van_Eyck_-_Portrait_of_a_Man_-_Self_Portrait.jpg/400px-Jan_van_Eyck_-_Portrait_of_a_Man_-_Self_Portrait.jpg"), _count: { works: 4 } },
  ],
  renaissance: [
    { id: "leonardo-da-vinci", name: "Leonardo da Vinci", birthYear: 1452, deathYear: 1519, nationality: "Italian", summary: "Italian polymath of the High Renaissance: painter, sculptor, architect, scientist, engineer.", movements: "Renaissance", portrait: WIKI("c/cc/Francesco_Melzi_-_Portrait_of_Leonardo_-_WGA14795.jpg/400px-Francesco_Melzi_-_Portrait_of_Leonardo_-_WGA14795.jpg"), _count: { works: 5 } },
    { id: "michelangelo", name: "Michelangelo Buonarroti", birthYear: 1475, deathYear: 1564, nationality: "Italian", summary: "Italian sculptor, painter, architect of the High Renaissance. Painted the Sistine Chapel ceiling.", movements: "Renaissance", portrait: WIKI("9/95/Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg/400px-Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg"), _count: { works: 5 } },
    { id: "raphael", name: "Raphael", birthYear: 1483, deathYear: 1520, nationality: "Italian", summary: "Italian painter and architect of the High Renaissance. Famous for Madonnas and large figure compositions.", movements: "Renaissance", portrait: WIKI("1/12/Raffaello_Sanzio.jpg/400px-Raffaello_Sanzio.jpg"), _count: { works: 5 } },
    { id: "botticelli", name: "Sandro Botticelli", birthYear: 1445, deathYear: 1510, nationality: "Italian", summary: "Italian Early Renaissance painter. Best known for The Birth of Venus and Primavera.", movements: "Renaissance", portrait: WIKI("d/d3/Sandro_Botticelli_083.jpg/400px-Sandro_Botticelli_083.jpg"), _count: { works: 5 } },
    { id: "titian", name: "Titian", birthYear: 1488, deathYear: 1576, nationality: "Italian", summary: "Italian painter of the Venetian school. Considered the most important member of the Venetian school.", movements: "Renaissance", portrait: WIKI("2/29/Titian_-_Self-Portrait_c._1567_-_WGA01775.jpg/400px-Titian_-_Self-Portrait_c._1567_-_WGA01775.jpg"), _count: { works: 5 } },
  ],
  baroque: [
    { id: "caravaggio", name: "Caravaggio", birthYear: 1571, deathYear: 1610, nationality: "Italian", summary: "Italian painter, active in Rome, Naples, Malta, and Sicily. Pioneer of tenebrism.", movements: "Baroque", portrait: WIKI("6/6e/1602-3 Caravaggio%2C Calling of Saint Matthew.jpg/400px-1602-3_Caravaggio%2C_Calling_of_Saint_Matthew.jpg"), _count: { works: 5 } },
    { id: "rembrandt", name: "Rembrandt van Rijn", birthYear: 1606, deathYear: 1669, nationality: "Dutch", summary: "Dutch Golden Age painter. Master of light, shadow, and human emotion.", movements: "Baroque", portrait: WIKI("4/4b/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg/400px-Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg"), _count: { works: 5 } },
    { id: "velazquez", name: "Diego Velázquez", birthYear: 1599, deathYear: 1660, nationality: "Spanish", summary: "Spanish painter, leading artist of the Spanish Golden Age. Court painter to the Spanish king.", movements: "Baroque", portrait: WIKI("3/32/Las_Meninas_01.jpg/400px-Las_Meninas_01.jpg"), _count: { works: 5 } },
    { id: "rubens", name: "Peter Paul Rubens", birthYear: 1577, deathYear: 1640, nationality: "Flemish", summary: "Flemish painter, considered the most influential artist of Flemish Baroque tradition.", movements: "Baroque", portrait: WIKI("3/3e/Peter_Paul_Rubens_-_Self-portrait_-_Google_Art_Project.jpg/400px-Peter_Paul_Rubens_-_Self-portrait_-_Google_Art_Project.jpg"), _count: { works: 5 } },
    { id: "vermeer", name: "Johannes Vermeer", birthYear: 1632, deathYear: 1675, nationality: "Dutch", summary: "Dutch Golden Age painter, known for his tranquil domestic scenes.", movements: "Baroque", portrait: WIKI("2/2f/Johannes_Vermeer_-_The_art_of_painting.jpg/400px-Johannes_Vermeer_-_The_art_of_painting.jpg"), _count: { works: 5 } },
  ],
  rococo: [
    { id: "watteau", name: "Jean-Antoine Watteau", birthYear: 1684, deathYear: 1721, nationality: "French", summary: "French painter whose subject matter was witty and often theatrical.", movements: "Rococo", portrait: WIKI("7/77/Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg/400px-Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg"), _count: { works: 4 } },
    { id: "boucher", name: "François Boucher", birthYear: 1703, deathYear: 1770, nationality: "French", summary: "French painter, a proponent of Rococo style, known for pastoral and mythological scenes.", movements: "Rococo", portrait: WIKI("b/b9/Fran%C3%A7ois_Boucher_-_Madame_de_Pompadour.jpg/400px-Fran%C3%A7ois_Boucher_-_Madame_de_Pompadour.jpg"), _count: { works: 4 } },
    { id: "fragonard", name: "Jean-Honoré Fragonard", birthYear: 1732, deathYear: 1806, nationality: "French", summary: "French painter and printmaker, whose late Rococo style was both playful and dramatic.", movements: "Rococo", portrait: WIKI("6/63/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg/400px-Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg"), _count: { works: 4 } },
  ],
  neoclassicism: [
    { id: "david", name: "Jacques-Louis David", birthYear: 1748, deathYear: 1825, nationality: "French", summary: "French painter in the Neoclassical style, considered the leading painter of his generation.", movements: "Neoclassicism", portrait: WIKI("2/27/Jacques-Louis_David_-_Self-portrait.jpg/400px-Jacques-Louis_David_-_Self-portrait.jpg"), _count: { works: 4 } },
    { id: "ingres", name: "Jean-Auguste-Dominique Ingres", birthYear: 1780, deathYear: 1867, nationality: "French", summary: "French Neoclassical painter, known for his portraits and historical paintings.", movements: "Neoclassicism", portrait: WIKI("4/45/Jean-Auguste-Dominique_Ingres_-_Self-portrait.jpg/400px-Jean-Auguste-Dominique_Ingres_-_Self-portrait.jpg"), _count: { works: 4 } },
  ],
  romanticism: [
    { id: "delacroix", name: "Eugène Delacroix", birthYear: 1798, deathYear: 1863, nationality: "French", summary: "French Romantic artist regarded as the leader of the French Romantic school.", movements: "Romanticism", portrait: WIKI("5/5e/Eug%C3%A8ne_Delacroix_-_Self-portrait_(c.1837).jpg/400px-Eug%C3%A8ne_Delacroix_-_Self-portrait_(c.1837).jpg"), _count: { works: 4 } },
    { id: "friedrich", name: "Caspar David Friedrich", birthYear: 1774, deathYear: 1840, nationality: "German", summary: "German Romantic landscape painter, generally considered the most important German artist of his generation.", movements: "Romanticism", portrait: WIKI("5/5c/Caspar_David_Friedrich_-_Self-portrait.jpg/400px-Caspar_David_Friedrich_-_Self-portrait.jpg"), _count: { works: 4 } },
    { id: "turner", name: "J.M.W. Turner", birthYear: 1775, deathYear: 1851, nationality: "British", summary: "English Romantic painter, printmaker and watercolourist, known for his expressive colourisation.", movements: "Romanticism", portrait: WIKI("7/7e/J._M._W._Turner_-_Self-Portrait.jpg/400px-J._M._W._Turner_-_Self-Portrait.jpg"), _count: { works: 4 } },
    { id: "gericault", name: "Théodore Géricault", birthYear: 1791, deathYear: 1824, nationality: "French", summary: "French painter and lithographer, known for his paintings of the Romantic style.", movements: "Romanticism", portrait: WIKI("0/05/Th%C3%A9odore_G%C3%A9ricault_-_Self-portrait.jpg/400px-Th%C3%A9odore_G%C3%A9ricault_-_Self-portrait.jpg"), _count: { works: 4 } },
  ],
  realism: [
    { id: "courbet", name: "Gustave Courbet", birthYear: 1819, deathYear: 1877, nationality: "French", summary: "French painter who led the Realism movement in 19th-century French painting.", movements: "Realism", portrait: WIKI("3/3a/Gustave_Courbet_-_Self-portrait_(The_Desperate_Man).jpg/400px-Gustave_Courbet_-_Self-portrait_(The_Desperate_Man).jpg"), _count: { works: 4 } },
    { id: "millet", name: "Jean-François Millet", birthYear: 1814, deathYear: 1875, nationality: "French", summary: "French painter and one of the founders of the Barbizon school in rural France.", movements: "Realism", portrait: WIKI("a/a2/Jean-Fran%C3%A7ois_Millet_-_Self-Portrait.jpg/400px-Jean-Fran%C3%A7ois_Millet_-_Self-Portrait.jpg"), _count: { works: 4 } },
  ],
  impressionism: [
    { id: "monet", name: "Claude Monet", birthYear: 1840, deathYear: 1926, nationality: "French", summary: "French painter, founder of Impressionism. Famous for water lilies and haystacks series.", movements: "Impressionism", portrait: WIKI("1/1a/Claude_Monet_1899_Nadar_crop.jpg/400px-Claude_Monet_1899_Nadar_crop.jpg"), _count: { works: 5 } },
    { id: "degas", name: "Edgar Degas", birthYear: 1834, deathYear: 1917, nationality: "French", summary: "French artist, one of founders of Impressionism, known for pastels and dance subjects.", movements: "Impressionism", portrait: WIKI("a/a1/Edgar_Degas_self-portrait.jpg/400px-Edgar_Degas_self-portrait.jpg"), _count: { works: 5 } },
    { id: "renoir", name: "Pierre-Auguste Renoir", birthYear: 1841, deathYear: 1919, nationality: "French", summary: "French painter, leading figure in Impressionism. Known for vibrant light and saturated color.", movements: "Impressionism", portrait: WIKI("9/9b/Pierre-Auguste_Renoir%2C_by_Pierre-Auguste_Renoir.jpg/400px-Pierre-Auguste_Renoir%2C_by_Pierre-Auguste_Renoir.jpg"), _count: { works: 5 } },
    { id: "manet", name: "Édouard Manet", birthYear: 1832, deathYear: 1883, nationality: "French", summary: "French modernist painter, transition between Realism and Impressionism.", movements: "Impressionism", portrait: WIKI("a/ac/Edouard_Manet_-_Self-portrait_with_Palette_-_Google_Art_Project.jpg/400px-Edouard_Manet_-_Self-portrait_with_Palette_-_Google_Art_Project.jpg"), _count: { works: 5 } },
    { id: "pissarro", name: "Camille Pissarro", birthYear: 1830, deathYear: 1903, nationality: "French", summary: "Danish-French painter, key figure in Impressionism and Neo-Impressionism.", movements: "Impressionism", portrait: WIKI("c/c8/Camille_Pissarro_001.jpg/400px-Camille_Pissarro_001.jpg"), _count: { works: 5 } },
  ],
  "post-impressionism": [
    { id: "van-gogh", name: "Vincent van Gogh", birthYear: 1853, deathYear: 1890, nationality: "Dutch", summary: "Dutch Post-Impressionist painter, among the most famous and influential figures in Western art history.", movements: "Post-Impressionism", portrait: WIKI("3/30/Vincent_van_Gogh_self-portrait.jpg/400px-Vincent_van_Gogh_self-portrait.jpg"), _count: { works: 5 } },
    { id: "cezanne", name: "Paul Cézanne", birthYear: 1839, deathYear: 1906, nationality: "French", summary: "French Post-Impressionist painter, whose work laid foundations for transition to Cubism.", movements: "Post-Impressionism", portrait: WIKI("1/14/Paul_Cezanne%2C_Self-portrait_1885.jpg/400px-Paul_Cezanne%2C_Self-portrait_1885.jpg"), _count: { works: 5 } },
    { id: "gauguin", name: "Paul Gauguin", birthYear: 1848, deathYear: 1903, nationality: "French", summary: "French Post-Impressionist artist, not appreciated until after his death.", movements: "Post-Impressionism", portrait: WIKI("6/6c/Paul_Gauguin_111_hr.jpg/400px-Paul_Gauguin_111_hr.jpg"), _count: { works: 5 } },
    { id: "seurat", name: "Georges Seurat", birthYear: 1859, deathYear: 1891, nationality: "French", summary: "French Post-Impressionist artist, pioneer of Pointillism technique.", movements: "Post-Impressionism", portrait: WIKI("2/27/Georges_Seurat_1888.jpg/400px-Georges_Seurat_1888.jpg"), _count: { works: 5 } },
  ],
  expressionism: [
    { id: "munch", name: "Edvard Munch", birthYear: 1863, deathYear: 1944, nationality: "Norwegian", summary: "Norwegian painter, best known for The Scream, one of the most iconic images of modern art.", movements: "Expressionism", portrait: WIKI("8/8d/Edvard_Munch_Selbstportrait.jpg/400px-Edvard_Munch_Selbstportrait.jpg"), _count: { works: 4 } },
    { id: "kandinsky", name: "Wassily Kandinsky", birthYear: 1866, deathYear: 1944, nationality: "Russian", summary: "Russian painter and art theorist, considered the father of abstract art.", movements: "Expressionism", portrait: WIKI("0/02/Vassily_Kandinsky%2C_self-portrait.jpg/400px-Vassily_Kandinsky%2C_self-portrait.jpg"), _count: { works: 4 } },
    { id: "kirchner", name: "Ernst Ludwig Kirchner", birthYear: 1880, deathYear: 1938, nationality: "German", summary: "German expressionist painter and printmaker, founding member of Die Brücke.", movements: "Expressionism", portrait: WIKI("3/35/Ernst_Ludwig_Kirchner.jpg/400px-Ernst_Ludwig_Kirchner.jpg"), _count: { works: 4 } },
  ],
  cubism: [
    { id: "picasso", name: "Pablo Picasso", birthYear: 1881, deathYear: 1973, nationality: "Spanish", summary: "Spanish painter, sculptor, co-founder of Cubism. One of the most influential artists of the 20th century.", movements: "Cubism", portrait: WIKI("9/9c/Pablo_picasso_1.jpg/400px-Pablo_picasso_1.jpg"), _count: { works: 5 } },
    { id: "braque", name: "Georges Braque", birthYear: 1882, deathYear: 1963, nationality: "French", summary: "French painter and sculptor, co-founder of Cubism with Picasso.", movements: "Cubism", portrait: WIKI("9/9e/Georges_Braque%2C_1908%2C_photo_portrait_%28autochrome%29.jpg/400px-Georges_Braque%2C_1908%2C_photo_portrait_%28autochrome%29.jpg"), _count: { works: 5 } },
    { id: "gris", name: "Juan Gris", birthYear: 1887, deathYear: 1927, nationality: "Spanish", summary: "Spanish painter, among the leading figures of the Cubist movement.", movements: "Cubism", portrait: WIKI("4/4d/Juan_Gris_-_Self_portrait.jpg/400px-Juan_Gris_-_Self_portrait.jpg"), _count: { works: 5 } },
  ],
  surrealism: [
    { id: "dali", name: "Salvador Dalí", birthYear: 1904, deathYear: 1989, nationality: "Spanish", summary: "Spanish surrealist artist, renowned for his technical skill and bizarre imagery.", movements: "Surrealism", portrait: WIKI("1/19/Salvador_Dal%C3%AD_1939.jpg/400px-Salvador_Dal%C3%AD_1939.jpg"), _count: { works: 4 } },
    { id: "magritte", name: "René Magritte", birthYear: 1898, deathYear: 1967, nationality: "Belgian", summary: "Belgian surrealist artist, known for challenging observers' preconditioned perceptions of reality.", movements: "Surrealism", portrait: WIKI("5/53/Magritte_photograph.jpg/400px-Magritte_photograph.jpg"), _count: { works: 4 } },
    { id: "ernst", name: "Max Ernst", birthYear: 1891, deathYear: 1976, nationality: "German", summary: "German painter, sculptor, and poet, a primary pioneer of Surrealism.", movements: "Surrealism", portrait: WIKI("4/4e/Max_Ernst_self-portrait.jpg/400px-Max_Ernst_self-portrait.jpg"), _count: { works: 4 } },
  ],
  "abstract-expressionism": [
    { id: "pollock", name: "Jackson Pollock", birthYear: 1912, deathYear: 1956, nationality: "American", summary: "American painter, leading figure in abstract expressionism. Famous for drip technique.", movements: "Abstract Expressionism", portrait: WIKI("8/86/Jackson_Pollock_Index_2.jpg/400px-Jackson_Pollock_Index_2.jpg"), _count: { works: 4 } },
    { id: "rothko", name: "Mark Rothko", birthYear: 1903, deathYear: 1970, nationality: "American", summary: "American abstract painter, best known for color field paintings.", movements: "Abstract Expressionism", portrait: WIKI("0/06/Mark_Rothko_1957.jpg/400px-Mark_Rothko_1957.jpg"), _count: { works: 4 } },
    { id: "de-kooning", name: "Willem de Kooning", birthYear: 1904, deathYear: 1997, nationality: "American", summary: "Dutch-American abstract expressionist artist, completed Woman series.", movements: "Abstract Expressionism", portrait: WIKI("b/b5/Willem_de_Kooning_in_his_studio.jpg/400px-Willem_de_Kooning_in_his_studio.jpg"), _count: { works: 4 } },
  ],
  "pop-art": [
    { id: "warhol", name: "Andy Warhol", birthYear: 1928, deathYear: 1987, nationality: "American", summary: "American visual artist, leading figure in pop art. Famous for Marilyn Diptych and Campbell's Soup Cans.", movements: "Pop Art", portrait: WIKI("3/3b/Andy_Warhol_1975.jpg/400px-Andy_Warhol_1975.jpg"), _count: { works: 4 } },
    { id: "lichtenstein", name: "Roy Lichtenstein", birthYear: 1923, deathYear: 1997, nationality: "American", summary: "American pop artist, known for his comic-inspired works with Ben-Day dots.", movements: "Pop Art", portrait: WIKI("6/6f/Roy_Lichtenstein_1.jpg/400px-Roy_Lichtenstein_1.jpg"), _count: { works: 4 } },
  ],
};

// Curated Wikipedia Commons painting URLs per artist (real, public-domain works)
export const DEMO_WORKS = {
  "leonardo-da-vinci": [
    { id: "mona-lisa", title: "Mona Lisa", year: 1503, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", width: 800, height: 1180, medium: "Oil on poplar panel" },
    { id: "last-supper", title: "The Last Supper", year: 1498, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/1280px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/1280px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg", width: 1280, height: 740, medium: "Tempera on wall" },
    { id: "vitruvian-man", title: "Vitruvian Man", year: 1490, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg/600px-Da_Vinci_Vitruve_Luc_Viatour.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg/600px-Da_Vinci_Vitruve_Luc_Viatour.jpg", width: 600, height: 776, medium: "Pen and ink on paper" },
    { id: "annunciation", title: "Annunciation", year: 1475, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg/1280px-Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg/1280px-Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg", width: 1280, height: 870, medium: "Oil on panel" },
    { id: "lady-er", title: "Lady with an Ermine", year: 1489, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg/600px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg/600px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg", width: 600, height: 800, medium: "Oil on panel" },
  ],
  "michelangelo": [
    { id: "creation-adam", title: "The Creation of Adam", year: 1512, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/1280px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/1280px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg", width: 1280, height: 800, medium: "Fresco" },
    { id: "pieta", title: "Pietà", year: 1499, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg/600px-Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg/600px-Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg", width: 600, height: 800, medium: "Marble sculpture" },
    { id: "david", title: "David", year: 1504, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Michelangelo%27s_David_-_right_view_2.jpg/600px-Michelangelo%27s_David_-_right_view_2.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Michelangelo%27s_David_-_right_view_2.jpg/600px-Michelangelo%27s_David_-_right_view_2.jpg", width: 600, height: 1200, medium: "Marble sculpture" },
    { id: "last-judgment", title: "The Last Judgment", year: 1541, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Michelangelo_-_Last_Judgement.jpg/800px-Michelangelo_-_Last_Judgement.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Michelangelo_-_Last_Judgement.jpg/800px-Michelangelo_-_Last_Judgement.jpg", width: 800, height: 1100, medium: "Fresco" },
    { id: "holy-family", title: "Doni Tondo (Holy Family)", year: 1507, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Michelangelo_Doni_Tondo.jpg/800px-Michelangelo_Doni_Tondo.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Michelangelo_Doni_Tondo.jpg/800px-Michelangelo_Doni_Tondo.jpg", width: 800, height: 800, medium: "Oil and tempera on panel" },
  ],
  "raphael": [
    { id: "school-athens", title: "The School of Athens", year: 1511, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sanzio_01.jpg/1280px-Sanzio_01.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sanzio_01.jpg/1280px-Sanzio_01.jpg", width: 1280, height: 800, medium: "Fresco" },
    { id: "sistine-madonna", title: "Sistine Madonna", year: 1512, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Sanzio_-_Sistine_Madonna.jpg/600px-Sanzio_-_Sistine_Madonna.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Sanzio_-_Sistine_Madonna.jpg/600px-Sanzio_-_Sistine_Madonna.jpg", width: 600, height: 880, medium: "Oil on canvas" },
    { id: "transfiguration", title: "The Transfiguration", year: 1520, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Raffaello_-_Trasfigurazione_-_Google_Art_Project.jpg/800px-Raffaello_-_Trasfigurazione_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Raffaello_-_Trasfigurazione_-_Google_Art_Project.jpg/800px-Raffaello_-_Trasfigurazione_-_Google_Art_Project.jpg", width: 800, height: 1000, medium: "Oil on panel" },
    { id: "madonna-goldfinch", title: "Madonna del Cardellino", year: 1506, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Raphael_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg/800px-Raphael_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Raphael_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg/800px-Raphael_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg", width: 800, height: 600, medium: "Oil on panel" },
    { id: "portrait-baldassare", title: "Portrait of Baldassare Castiglione", year: 1514, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Raffaello%2C_portrait_of_baldassare_castiglione.jpg/600px-Raffaello%2C_portrait_of_baldassare_castiglione.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Raffaello%2C_portrait_of_baldassare_castiglione.jpg/600px-Raffaello%2C_portrait_of_baldassare_castiglione.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "van-gogh": [
    { id: "starry-night", title: "The Starry Night", year: 1889, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", width: 1280, height: 1014, medium: "Oil on canvas" },
    { id: "sunflowers", title: "Sunflowers", year: 1888, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/800px-Vincent_Willem_van_Gogh_127.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/800px-Vincent_Willem_van_Gogh_127.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
    { id: "cafe-terrace", title: "Café Terrace at Night", year: 1888, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Vincent_van_Gogh_-_Caf%C3%A9_Terrace_at_Night_%28Yorck%29.jpg/800px-Vincent_van_Gogh_-_Caf%C3%A9_Terrace_at_Night_%28Yorck%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Vincent_van_Gogh_-_Caf%C3%A9_Terrace_at_Night_%28Yorck%29.jpg/800px-Vincent_van_Gogh_-_Caf%C3%A9_Terrace_at_Night_%28Yorck%29.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
    { id: "bedroom", title: "Bedroom in Arles", year: 1888, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg/1024px-Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg/1024px-Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg", width: 1024, height: 800, medium: "Oil on canvas" },
    { id: "wheatfield-crows", title: "Wheatfield with Crows", year: 1890, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Vincent_van_Gogh_%281853-1890%29_-_Wheat_Field_with_Crows_%281890%29.jpg/1024px-Vincent_van_Gogh_%281853-1890%29_-_Wheat_Field_with_Crows_%281890%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Vincent_van_Gogh_%281853-1890%29_-_Wheat_Field_with_Crows_%281890%29.jpg/1024px-Vincent_van_Gogh_%281853-1890%29_-_Wheat_Field_with_Crows_%281890%29.jpg", width: 1024, height: 640, medium: "Oil on canvas" },
  ],
  "monet": [
    { id: "water-lilies", title: "Water Lilies", year: 1906, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1280px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1280px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg", width: 1280, height: 1000, medium: "Oil on canvas" },
    { id: "impression-sunrise", title: "Impression, Sunrise", year: 1872, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg", width: 1280, height: 920, medium: "Oil on canvas" },
    { id: "haystacks", title: "Haystacks (Effect of Snow and Sun)", year: 1891, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Claude_Monet_-_Haystacks_Snow_Effect_-_Google_Art_Project.jpg/1024px-Claude_Monet_-_Haystacks_Snow_Effect_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Claude_Monet_-_Haystacks_Snow_Effect_-_Google_Art_Project.jpg/1024px-Claude_Monet_-_Haystacks_Snow_Effect_-_Google_Art_Project.jpg", width: 1024, height: 800, medium: "Oil on canvas" },
    { id: "rouen-cathedral", title: "Rouen Cathedral, Full Sunlight", year: 1894, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Claude_Monet_-_Rouen_Cathedral%2C_Full_Sunlight.jpg/800px-Claude_Monet_-_Rouen_Cathedral%2C_Full_Sunlight.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Claude_Monet_-_Rouen_Cathedral%2C_Full_Sunlight.jpg/800px-Claude_Monet_-_Rouen_Cathedral%2C_Full_Sunlight.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
    { id: "japanese-bridge", title: "The Japanese Bridge", year: 1899, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Claude_Monet_-_Japanese_Bridge_-_Google_Art_Project.jpg/800px-Claude_Monet_-_Japanese_Bridge_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Claude_Monet_-_Japanese_Bridge_-_Google_Art_Project.jpg/800px-Claude_Monet_-_Japanese_Bridge_-_Google_Art_Project.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "picasso": [
    { id: "guernica", title: "Guernica", year: 1937, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/1280px-PicassoGuernica.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/1280px-PicassoGuernica.jpg", width: 1280, height: 770, medium: "Oil on canvas" },
    { id: "demoiselles", title: "Les Demoiselles d'Avignon", year: 1907, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Les_Demoiselles_d%27Avignon.jpg/1024px-Les_Demoiselles_d%27Avignon.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Les_Demoiselles_d%27Avignon.jpg/1024px-Les_Demoiselles_d%27Avignon.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
    { id: "old-guitarist", title: "The Old Guitarist", year: 1904, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Old_guitarist_Picasso.jpg/600px-Old_guitarist_Picasso.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Old_guitarist_Picasso.jpg/600px-Old_guitarist_Picasso.jpg", width: 600, height: 800, medium: "Oil on panel" },
    { id: "weeping-woman", title: "Weeping Woman", year: 1937, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Picasso_The_Weeping_Woman_Tate_identifier_T05010_2.jpg/600px-Picasso_The_Weeping_Woman_Tate_identifier_T05010_2.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Picasso_The_Weeping_Woman_Tate_identifier_T05010_2.jpg/600px-Picasso_The_Weeping_Woman_Tate_identifier_T05010_2.jpg", width: 600, height: 800, medium: "Oil on canvas" },
    { id: "girl-mirror", title: "Girl Before a Mirror", year: 1932, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/La_Girl_Before_Mirror.jpg/600px-La_Girl_Before_Mirror.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/La_Girl_Before_Mirror.jpg/600px-La_Girl_Before_Mirror.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "vermeer": [
    { id: "girl-pearl", title: "Girl with a Pearl Earring", year: 1665, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/600px-1665_Girl_with_a_Pearl_Earring.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/600px-1665_Girl_with_a_Pearl_Earring.jpg", width: 600, height: 750, medium: "Oil on canvas" },
    { id: "milkmaid", title: "The Milkmaid", year: 1658, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/600px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/600px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg", width: 600, height: 720, medium: "Oil on canvas" },
    { id: "art-painting", title: "The Art of Painting", year: 1668, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Vermeer-view-of-delft.jpg/1024px-Vermeer-view-of-delft.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Vermeer-view-of-delft.jpg/1024px-Vermeer-view-of-delft.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
    { id: "view-delft", title: "View of Delft", year: 1661, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Vermeer-view-of-delft.jpg/1024px-Vermeer-view-of-delft.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Vermeer-view-of-delft.jpg/1024px-Vermeer-view-of-delft.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
  ],
};

// Fallback: her sanatçı için 4 generic "painting" placeholder (Commons'tan bilinen ünlü resimler)
const FALLBACK_WORKS = {
  "giotto-di-bondone": [
    { id: "giotto-1", title: "Lamentation (The Dead Christ)", year: 1305, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Dead_Christ%29.jpg/1024px-Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Dead_Christ%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Dead_Christ%29.jpg/1024px-Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Dead_Christ%29.jpg", width: 1024, height: 770, medium: "Fresco" },
  ],
  "duccio-di-buoninsegna": [
    { id: "duccio-1", title: "Maestà", year: 1308, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Duccio_di_Buoninsegna_-_Maest%C3%A0_-_Google_Art_Project-edit1.jpg/1024px-Duccio_di_Buoninsegna_-_Maest%C3%A0_-_Google_Art_Project-edit1.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Duccio_di_Buoninsegna_-_Maest%C3%A0_-_Google_Art_Project-edit1.jpg/1024px-Duccio_di_Buoninsegna_-_Maest%C3%A0_-_Google_Art_Project-edit1.jpg", width: 1024, height: 600, medium: "Tempera on panel" },
  ],
  "jan-van-eyck": [
    { id: "eyck-arnolfini", title: "Arnolfini Portrait", year: 1434, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/600px-Van_Eyck_-_Arnolfini_Portrait.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/600px-Van_Eyck_-_Arnolfini_Portrait.jpg", width: 600, height: 800, medium: "Oil on oak panel" },
    { id: "eyck-ghent", title: "Ghent Altarpiece (Adoration of Mystic Lamb)", year: 1432, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/VanEyck_Ghent_AdorationOfMysticLamb.jpg/1024px-VanEyck_Ghent_AdorationOfMysticLamb.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/VanEyck_Ghent_AdorationOfMysticLamb.jpg/1024px-VanEyck_Ghent_AdorationOfMysticLamb.jpg", width: 1024, height: 600, medium: "Oil on panel" },
  ],
  "botticelli": [
    { id: "botticelli-venus", title: "The Birth of Venus", year: 1485, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg", width: 1280, height: 800, medium: "Tempera on canvas" },
    { id: "botticelli-primavera", title: "Primavera", year: 1482, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Botticelli-primavera.jpg/1280px-Botticelli-primavera.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Botticelli-primavera.jpg/1280px-Botticelli-primavera.jpg", width: 1280, height: 800, medium: "Tempera on panel" },
  ],
  "titian": [
    { id: "titian-venus", title: "Venus of Urbino", year: 1534, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Tiziano_002.jpg/1024px-Tiziano_002.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Tiziano_002.jpg/1024px-Tiziano_002.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
    { id: "titian-bacchus", title: "Bacchus and Ariadne", year: 1523, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Titian_Bacchus_and_Ariadne.jpg/1024px-Titian_Bacchus_and_Ariadne.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Titian_Bacchus_and_Ariadne.jpg/1024px-Titian_Bacchus_and_Ariadne.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
  ],
  "caravaggio": [
    { id: "caravaggio-judith", title: "Judith Beheading Holofernes", year: 1599, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Caravaggio_-_Giuditta_decapita_Oloferne.jpg/1024px-Caravaggio_-_Giuditta_decapita_Oloferne.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Caravaggio_-_Giuditta_decapita_Oloferne.jpg/1024px-Caravaggio_-_Giuditta_decapita_Oloferne.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
    { id: "caravaggio-calling", title: "The Calling of Saint Matthew", year: 1600, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Caravaggio_-_La_vocazione_di_San_Matteo.jpg/1024px-Caravaggio_-_La_vocazione_di_San_Matteo.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Caravaggio_-_La_vocazione_di_San_Matteo.jpg/1024px-Caravaggio_-_La_vocazione_di_San_Matteo.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
  ],
  "rembrandt": [
    { id: "rembrandt-night-watch", title: "The Night Watch", year: 1642, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/The_Night_Watch_-_HD.jpg/1280px-The_Night_Watch_-_HD.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/The_Night_Watch_-_HD.jpg/1280px-The_Night_Watch_-_HD.jpg", width: 1280, height: 800, medium: "Oil on canvas" },
    { id: "rembrandt-philosopher", title: "Philosopher in Meditation", year: 1632, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/REMBRANDT_-_Fil%C3%B3sofo_en_Meditaci%C3%B3n_%28National_Gallery%2C_Londres%2C_1632%29.jpg/800px-REMBRANDT_-_Fil%C3%B3sofo_en_Meditaci%C3%B3n_%28National_Gallery%2C_Londres%2C_1632%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/REMBRANDT_-_Fil%C3%B3sofo_en_Meditaci%C3%B3n_%28National_Gallery%2C_Londres%2C_1632%29.jpg/800px-REMBRANDT_-_Fil%C3%B3sofo_en_Meditaci%C3%B3n_%28National_Gallery%2C_Londres%2C_1632%29.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "velazquez": [
    { id: "velazquez-meninas", title: "Las Meninas", year: 1656, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas_01.jpg/800px-Las_Meninas_01.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas_01.jpg/800px-Las_Meninas_01.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
    { id: "velazquez-buffoons", title: "Portrait of Juan de Pareja", year: 1650, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Retrato_de_Juan_de_Pareja_%28by_Diego_Vel%C3%A1zquez%29.jpg/600px-Retrato_de_Juan_de_Pareja_%28by_Diego_Vel%C3%A1zquez%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Retrato_de_Juan_de_Pareja_%28by_Diego_Vel%C3%A1zquez%29.jpg/600px-Retrato_de_Juan_de_Pareja_%28by_Diego_Vel%C3%A1zquez%29.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "rubens": [
    { id: "rubens-judgment", title: "The Judgment of Paris", year: 1639, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Peter_Paul_Rubens_-_The_Judgment_of_Paris_-_WGA20253.jpg/1024px-Peter_Paul_Rubens_-_The_Judgment_of_Paris_-_WGA20253.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Peter_Paul_Rubens_-_The_Judgment_of_Paris_-_WGA20253.jpg/1024px-Peter_Paul_Rubens_-_The_Judgment_of_Paris_-_WGA20253.jpg", width: 1024, height: 760, medium: "Oil on panel" },
  ],
  "watteau": [
    { id: "watteau-pierrot", title: "Pierrot (Gilles)", year: 1718, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg/600px-Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg/600px-Jean-Antoine_Watteau_-_Pierrot_Gilles_-_Google_Art_Project.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "boucher": [
    { id: "boucher-odalisque", title: "Reclining Girl (L'Odalisque)", year: 1752, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/François_Boucher_-_Reclining_Girl_-_WGA2996.jpg/1024px-François_Boucher_-_Reclining_Girl_-_WGA2996.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/François_Boucher_-_Reclining_Girl_-_WGA2996.jpg/1024px-François_Boucher_-_Reclining_Girl_-_WGA2996.jpg", width: 1024, height: 720, medium: "Oil on canvas" },
  ],
  "fragonard": [
    { id: "fragonard-swing", title: "The Swing", year: 1767, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg/600px-Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg/600px-Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "david": [
    { id: "david-oath", title: "Oath of the Horatii", year: 1784, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg/1024px-Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg/1024px-Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg", width: 1024, height: 800, medium: "Oil on canvas" },
    { id: "david-marie", title: "The Death of Marat", year: 1793, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Death_of_Marat_by_David.jpg/600px-Death_of_Marat_by_David.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Death_of_Marat_by_David.jpg/600px-Death_of_Marat_by_David.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "ingres": [
    { id: "ingres-grande", title: "La Grande Odalisque", year: 1814, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Jean-Auguste-Dominique_Ingres%2C_La_Grande_Odalisque%2C_1814.jpg/1024px-Jean-Auguste-Dominique_Ingres%2C_La_Grande_Odalisque%2C_1814.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Jean-Auguste-Dominique_Ingres%2C_La_Grande_Odalisque%2C_1814.jpg/1024px-Jean-Auguste-Dominique_Ingres%2C_La_Grande_Odalisque%2C_1814.jpg", width: 1024, height: 680, medium: "Oil on canvas" },
  ],
  "delacroix": [
    { id: "delacroix-liberty", title: "Liberty Leading the People", year: 1830, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg", width: 1280, height: 800, medium: "Oil on canvas" },
  ],
  "friedrich": [
    { id: "friedrich-fog", title: "Wanderer above the Sea of Fog", year: 1818, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "turner": [
    { id: "turner-rain", title: "Rain, Steam and Speed", year: 1844, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/J._M._W._Turner_-_Rain%2C_Steam_and_Speed_-_Google_Art_Project.jpg/1024px-J._M._W._Turner_-_Rain%2C_Steam_and_Speed_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/J._M._W._Turner_-_Rain%2C_Steam_and_Speed_-_Google_Art_Project.jpg/1024px-J._M._W._Turner_-_Rain%2C_Steam_and_Speed_-_Google_Art_Project.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
  ],
  "gericault": [
    { id: "gericault-raft", title: "The Raft of the Medusa", year: 1819, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Th%C3%A9odore_G%C3%A9ricault_-_Le_Radeau_de_La_M%C3%A9duse.jpg/1280px-Th%C3%A9odore_G%C3%A9ricault_-_Le_Radeau_de_La_M%C3%A9duse.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Th%C3%A9odore_G%C3%A9ricault_-_Le_Radeau_de_La_M%C3%A9duse.jpg/1280px-Th%C3%A9odore_G%C3%A9ricault_-_Le_Radeau_de_La_M%C3%A9duse.jpg", width: 1280, height: 800, medium: "Oil on canvas" },
  ],
  "courbet": [
    { id: "courbet-studio", title: "The Painter's Studio", year: 1855, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Gustave_Courbet_-_L%27Atelier_du_peintre_-_Google_Art_Project.jpg/1024px-Gustave_Courbet_-_L%27Atelier_du_peintre_-_Google_Art_Project.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Gustave_Courbet_-_L%27Atelier_du_peintre_-_Google_Art_Project.jpg/1024px-Gustave_Courbet_-_L%27Atelier_du_peintre_-_Google_Art_Project.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
  ],
  "millet": [
    { id: "millet-angelus", title: "The Angelus", year: 1857, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus.jpg/600px-Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus.jpg/600px-Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "degas": [
    { id: "degas-ballet", title: "The Dance Class", year: 1874, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Edgar_Degas_-_La_Classe_de_danse.jpg/1024px-Edgar_Degas_-_La_Classe_de_danse.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Edgar_Degas_-_La_Classe_de_danse.jpg/1024px-Edgar_Degas_-_La_Classe_de_danse.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
  ],
  "renoir": [
    { id: "renoir-bal", title: "Bal du moulin de la Galette", year: 1876, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/1280px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/1280px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg", width: 1280, height: 800, medium: "Oil on canvas" },
  ],
  "manet": [
    { id: "manet-olympia", title: "Olympia", year: 1863, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg/1024px-Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg/1024px-Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
  ],
  "pissarro": [
    { id: "pissarro-boulevard", title: "Boulevard Montmartre, Spring", year: 1897, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring.jpg/1024px-Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring.jpg/1024px-Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
  ],
  "cezanne": [
    { id: "cezanne-cardplayers", title: "The Card Players", year: 1895, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Paul_C%C3%A9zanne%2C_Les_joueurs_de_carte_%281892-95%29.jpg/1024px-Paul_C%C3%A9zanne%2C_Les_joueurs_de_carte_%281892-95%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Paul_C%C3%A9zanne%2C_Les_joueurs_de_carte_%281892-95%29.jpg/1024px-Paul_C%C3%A9zanne%2C_Les_joueurs_de_carte_%281892-95%29.jpg", width: 1024, height: 800, medium: "Oil on canvas" },
  ],
  "gauguin": [
    { id: "gauguin-tahiti", title: "Where Do We Come From? What Are We? Where Are We Going?", year: 1897, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Paul_Gauguin_-_D%27ou_venons-nous.jpg/1280px-Paul_Gauguin_-_D%27ou_venons-nous.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Paul_Gauguin_-_D%27ou_venons-nous.jpg/1280px-Paul_Gauguin_-_D%27ou_venons-nous.jpg", width: 1280, height: 500, medium: "Oil on canvas" },
  ],
  "seurat": [
    { id: "seurat-sunday", title: "A Sunday Afternoon on the Island of La Grande Jatte", year: 1886, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg", width: 1280, height: 480, medium: "Oil on canvas" },
  ],
  "munch": [
    { id: "munch-scream", title: "The Scream", year: 1893, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/600px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/600px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg", width: 600, height: 800, medium: "Oil, tempera, pastel" },
  ],
  "kandinsky": [
    { id: "kandinsky-composition", title: "Composition VIII", year: 1923, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg/1024px-Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg/1024px-Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg", width: 1024, height: 700, medium: "Oil on canvas" },
  ],
  "kirchner": [
    { id: "kirchner-street", title: "Street, Berlin", year: 1913, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/El_Lissitzky_und_Ernst_Ludwig_Kirchner.jpg/800px-El_Lissitzky_und_Ernst_Ludwig_Kirchner.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/El_Lissitzky_und_Ernst_Ludwig_Kirchner.jpg/800px-El_Lissitzky_und_Ernst_Ludwig_Kirchner.jpg", width: 800, height: 600, medium: "Oil on canvas" },
  ],
  "braque": [
    { id: "braque-violin", title: "Violin and Candlestick", year: 1910, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Georges_Braque%2C_1910%2C_Violin_and_Candlestick%2C_San_Francisco.jpg/800px-Georges_Braque%2C_1910%2C_Violin_and_Candlestick%2C_San_Francisco.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Georges_Braque%2C_1910%2C_Violin_and_Candlestick%2C_San_Francisco.jpg/800px-Georges_Braque%2C_1910%2C_Violin_and_Candlestick%2C_San_Francisco.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "gris": [
    { id: "gris-portrait", title: "Portrait of Pablo Picasso", year: 1912, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Portrait_of_Pablo_Picasso%2C_1912.jpg/800px-Portrait_of_Pablo_Picasso%2C_1912.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Portrait_of_Pablo_Picasso%2C_1912.jpg/800px-Portrait_of_Pablo_Picasso%2C_1912.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "dali": [
    { id: "dali-persistence", title: "The Persistence of Memory", year: 1931, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/1024px-The_Persistence_of_Memory.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/1024px-The_Persistence_of_Memory.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
    { id: "dali-elephants", title: "The Elephants", year: 1948, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/The_Elephants.jpg/1024px-The_Elephants.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/The_Elephants.jpg/1024px-The_Elephants.jpg", width: 1024, height: 760, medium: "Oil on canvas" },
  ],
  "magritte": [
    { id: "magritte-son", title: "The Son of Man", year: 1964, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Magritte_TheSonOfMan.jpg/600px-Magritte_TheSonOfMan.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Magritte_TheSonOfMan.jpg/600px-Magritte_TheSonOfMan.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "ernst": [
    { id: "ernst-elephant", title: "The Elephant Celebes", year: 1921, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Max_Ernst_-_The_Elephant_Celebes.jpg/1024px-Max_Ernst_-_The_Elephant_Celebes.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Max_Ernst_-_The_Ephant_Celebes.jpg/1024px-Max_Ernst_-_The_Elephant_Celebes.jpg", width: 1024, height: 800, medium: "Oil on canvas" },
  ],
  "pollock": [
    { id: "pollock-no5", title: "No. 5, 1948", year: 1948, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/No._5%2C_1948.jpg/1024px-No._5%2C_1948.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/No._5%2C_1948.jpg/1024px-No._5%2C_1948.jpg", width: 1024, height: 760, medium: "Oil on fiberboard" },
  ],
  "rothko": [
    { id: "rothko-orange", title: "Orange, Red, Yellow", year: 1961, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/MarkRothko-OrangeRedYellow.jpg/800px-MarkRothko-OrangeRedYellow.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/MarkRothko-OrangeRedYellow.jpg/800px-MarkRothko-OrangeRedYellow.jpg", width: 800, height: 1000, medium: "Oil on canvas" },
  ],
  "de-kooning": [
    { id: "de-kooning-woman", title: "Woman I", year: 1952, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Woman_I.jpg/600px-Woman_I.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Woman_I.jpg/600px-Woman_I.jpg", width: 600, height: 800, medium: "Oil on canvas" },
  ],
  "warhol": [
    { id: "warhol-marilyn", title: "Marilyn Diptych", year: 1962, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Marilyndiptych.jpg/1024px-Marilyndiptych.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Marilyndiptych.jpg/1024px-Marilyndiptych.jpg", width: 1024, height: 500, medium: "Acrylic on canvas" },
    { id: "warhol-soup", title: "Campbell's Soup Cans", year: 1962, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg/800px-Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg/800px-Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg", width: 800, height: 600, medium: "Synthetic polymer on canvas" },
  ],
  "lichtenstein": [
    { id: "lichtenstein-drowning", title: "Drowning Girl", year: 1963, imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Drowning_Girl_%28Roy_Lichtenstein%29.jpg/600px-Drowning_Girl_%28Roy_Lichtenstein%29.jpg", thumbUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Drowning_Girl_%28Roy_Lichtenstein%29.jpg/600px-Drowning_Girl_%28Roy_Lichtenstein%29.jpg", width: 600, height: 800, medium: "Oil and synthetic polymer on canvas" },
  ],
};

export function getWorksForArtist(artistId) {
  return DEMO_WORKS[artistId] || FALLBACK_WORKS[artistId] || [];
}
